# Generated by Django 3.0.4 on 2020-06-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerForm',
            new_name='PlayerClaim',
        ),
    ]
