# Generated by Django 3.0.4 on 2020-06-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_auto_20200603_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerclaim',
            name='profile',
        ),
    ]
