# Generated by Django 3.0.4 on 2020-06-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('buy', '0003_remove_playerclaim_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerclaim',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
