# Generated by Django 3.0.4 on 2020-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skin_thumb',
            field=models.CharField(blank=True, default='media/profile\\steve_100x100.png', max_length=255, verbose_name='Thumbnail image'),
        ),
    ]
